defaultBackgroundImage: "images/muir_woods_pano.jpg"

author:
  name: "Mike Witt"
  #   email = "mike@witt.gg"
  image: "images/dog_profile_AI_GEN.png"
  imageQuality: 96
  headline: "Human, often awkward"
  bio: "Electrical Engineer with eclectic hobbies (like most engineers)."